# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PvProspector
                                 A QGIS plugin
<<<<<<< HEAD
 Displays the PV installation potential for residential properties. The pv_area layer is derived from 1m LIDAR DSM, OSMM building outlines and LLPG data.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-11-05
        copyright            : (C) 2023 by Peter Francon
=======
 Displays the PV installation potential for residential properties across MK Borough
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-10-18
        copyright            : (C) 2023 by GeoMaptric
>>>>>>> 07c9ab8096792a958f0d5fd4a4abed5b0c8c8c60
        email                : peter@geomaptric.co.uk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PvProspector class from file PvProspector.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pv_prospector import PvProspector
    return PvProspector(iface)
